name : Demo

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: echo OI TATA
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.x.x' # SDK Version to use; x will use the latest version of the 3.1 channel
    - name: Install dependencies
      run: dotnet restore
    - name: Relsease
      run: dotnet build Web.Demo.csproj --configuration Release --no-restore
    - name: Publish
      run: dotnet publish Demo3/Web.Demo.csproj -c Release -o release — nologo
    - name: Upload Build Artifact
    - uses: actions/upload-artifact@v2
      with:
      - name: Application_Artifact
        path: /home/runner/work/Web.Demo/Demo3/release/